<img style="float: left; margin: 30px 15px 15px 15px;" src="https://pngimage.net/wp-content/uploads/2018/06/logo-iteso-png-5.png" width="300" height="500" /> 
    
    
### <font color='navy'> Simulación de procesos financieros. 

**Nombres:** Ana María Aguilera Gómez y Cuauhtémoc Corrales Camacho.

**Fecha:** 07 de septiembre del 2021.

**Expediente** : 720567 y 720482.
**Profesor:** Oscar David Jaramillo Zuluaga.
    
**Link Github**: https://github.com/anamaria1404/ProyectoConjunto_CCORRALES_AMAGUILERA_v2

# Tarea 2: Clase Optimización de Programación

## Enunciado de tarea 
> Indicaciones de creación de repositorio.

1. Imagine una rutina contable utilizada en una librería. Funciona en una lista con sublistas, que se ven así:
![imagen.png](attachment:imagen.png)
Escriba un programa en Python, que devuelve una lista con tuplas de tamaño 2. Cada tupla consiste en el número de pedido y el costo total del pedido. El producto debe aumentarse en 10€ si el valor de la orden es inferior a 100,00 €. 
Escribe un programa Python usando unicamente las funciones **lambda y map**.

`orders = [ ["34587", "Learning Python, Mark Lutz", 4, 40.95], 
           ["98762", "Programming Python, Mark Lutz", 5, 56.80], 
           ["77226", "Head First Python, Paul Barry", 3,32.95],
           ["88112", "Einführung in Python3, Bernd Klein", 3, 24.99]]`

In [17]:
orders = [ ["34587", "Learning Python, Mark Lutz", 4, 40.95], 
           ["98762", "Programming Python, Mark Lutz", 5, 56.80], 
           ["77226", "Head First Python, Paul Barry", 3,32.95],
           ["88112", "Einführung in Python3, Bernd Klein", 3, 24.99]]

In [18]:
# Código de solución estudiante 1: Ana María Aguilera
import numpy as np

#opción 1
res1=list(map(lambda i: list(map(lambda a: (orders[i][a],orders[i][a+2]*orders[i][a+3]) if (orders[i][a+2]*orders[i][a+3])>100 else (orders[i][a],orders[i][a+2]*orders[i][a+3]+10),range(1))), range(len(orders))))
res1

#opción 2
costo = lambda x,y: x*y
s = lambda a: a if a>=100 else a+10
x = list(map(s,[costo(orders[i][2], orders[i][3]) for i in np.arange(len(orders))]))
res2 = list(map(lambda x,y: (x[0],y),orders,x))
res2

[('34587', 163.8),
 ('98762', 284.0),
 ('77226', 108.85000000000001),
 ('88112', 84.97)]

In [11]:
# Código de solución estudiante 2
orders1 = [ ["34587", "Learning Python, Mark Lutz", 4, 40.95], 
           ["98762", "Programming Python, Mark Lutz", 5, 56.80], 
           ["77226", "Head First Python, Paul Barry", 3,32.95],
           ["88112", "Einführung in Python3, Bernd Klein", 3, 24.99]]

p = lambda x,y: x*y
def increase(value):
    if value < 100:
        value += 10
    return value

x = list([(orders1[i][0],increase(p(orders1[i][2],orders1[i][3]))) for i in np.arange(len(orders1))])
x

[('34587', 163.8),
 ('98762', 284.0),
 ('77226', 108.85000000000001),
 ('88112', 84.97)]

2. La misma librería, pero esta vez trabajamos en una lista diferente. Las sublistas de nuestras listas se ven así: 
[número de orden, (número de artículo, cantidad, precio por unidad), ... (número de artículo, cantidad, precio por unidad)] 

`orders = [[1, ("5464", 4, 9.99), ("8274",18,12.99), ("9744", 9, 44.95)], 
	       [2, ("5464", 9, 9.99), ("9744", 9, 44.95)],
	       [3, ("5464", 9, 9.99), ("88112", 11, 24.99)],
           [4, ("8732", 7, 11.99), ("7733",11,18.99), ("88112", 5, 39.95)] ]`

Escriba un programa que devuelva una lista de dos tuplas que tengan la información de (número de pedido, cantidad total de pedido). Utilice la función `Reduce`. Recuerde el precio del pedido del producto debe aumentarse en 10€ si el valor de la orden es inferior a 100,00 €.

In [19]:
orders2 = [[1, ("5464", 4, 9.99), ("8274",18,12.99), ("9744", 9, 44.95)], 
          [2, ("5464", 9, 9.99), ("9744", 9, 44.95)],
          [3, ("5464", 9, 9.99), ("88112", 11, 24.99)],
          [4, ("8732", 7, 11.99), ("7733",11,18.99), ("88112", 5, 39.95)] ]

In [21]:
# Código de solución estudiante 1: Ana María A.
from functools import reduce
r= list(map(lambda x: [x[0], reduce(lambda x,y: x+y, list(map(lambda x:x[1]*x[2] if x[1]*x[2]>100 else x[1]*x[2]+10, x[1:])))],orders2))
r

[[1, 688.3299999999999],
 [2, 504.46000000000004],
 [3, 374.79999999999995],
 [4, 502.57]]

In [7]:
# Código de solución estudiante 2
from functools import reduce
orders2 = [[1, ("5464", 4, 9.99), ("8274",18,12.99), ("9744", 9, 44.95)], 
          [2, ("5464", 9, 9.99), ("9744", 9, 44.95)],
          [3, ("5464", 9, 9.99), ("88112", 11, 24.99)],
          [4, ("8732", 7, 11.99), ("7733",11,18.99), ("88112", 5, 39.95)]]

result= list(map(lambda x: (x[0], reduce(lambda x,y: x+y, list(map(lambda x:x[1]*x[2] if x[1]*x[2]>100 else x[1]*x[2]+10, x[1:])))),orders2))

result

[(1, 688.3299999999999),
 (2, 504.46000000000004),
 (3, 374.79999999999995),
 (4, 502.57)]

3. Resolver los anteriores ejercicios usando pandas (DataFrame)

In [13]:
# Código de solución estudiante 1: Ana María A.
import pandas as pd

#ejercicio 1
df_orders = pd.DataFrame(orders)
s = lambda x: x if x>100 else x+10
tabla = {'No. orden': df_orders[0],'Costo total': (df_orders[2]*df_orders[3]).apply(s)}
tabla = pd.DataFrame(tabla)
tabla

No. orden  Costo total
0     34587       163.80
1     98762       284.00
2     77226       108.85
3     88112        84.97

In [16]:
# Código de solución estudiante 1: Ana María A.
# ejercicio 2

df2 = pd.DataFrame(orders2)
s = lambda x: x if x>100 else x+10
p1,p2,p3 = df2[1],df2[2],df2[3]
tabla = {'No. pedido': df2[0],'Costo total': [s(p1[0][1]*p1[0][2])+s(p2[0][1]*p2[0][2])+s(p3[0][1]*p3[0][2]),
                                             s(p1[1][1]*p1[1][2])+s(p2[1][1]*p2[1][2]),
                                             s(p1[2][1]*p1[2][2])+s(p2[2][1]*p2[2][2]),
                                             s(p1[3][1]*p1[3][2])+s(p2[3][1]*p2[3][2])+s(p3[3][1]*p3[3][2])]}
tabla = pd.DataFrame(tabla)
tabla

No. pedido  Costo total
0           1       688.33
1           2       504.46
2           3       374.80
3           4       502.57

In [14]:
# Código de solución estudiante 2
# Para Ejercicio 1
import pandas as pd

dt1 = pd.DataFrame(orders1)
dt1.columns = ['ID','Name','Number','Price']
dt1["Total_order"] = dt1['Number']*dt1['Price']
dt1["Total_order"] = dt1["Total_order"].apply(increase)
dt1 = dt1.drop(['Name','Number','Price'], axis=1)

# Para Ejercicio 2
o1 = orders2[0][1]
o2 = orders2[0][2]
o3 = orders2[0][3]
o4 = orders2[1][1]
o5 = orders2[1][2]
o6 = orders2[2][1]
o7 = orders2[2][2]
o8 = orders2[3][1]
o9 = orders2[3][2]
o10 = orders2[3][3]

dt2 = pd.DataFrame()

dt2['Num_orden'] = None
dt2['Subtotal1'] = None
dt2['Subtotal2'] = None
dt2['Subtotal3'] = None

dt2.loc['n1'] = [orders2[0][0], o1[1]*o1[2],o2[1]*o2[2],o3[1]*o3[2]]
dt2.loc['n2'] = [orders2[1][0], o4[1]*o4[2],o5[1]*o5[2],0]
dt2.loc['n3'] = [orders2[2][0], o6[1]*o6[2],o7[1]*o7[2],0]
dt2.loc['n4'] = [orders2[3][0], o8[1]*o8[2],o9[1]*o9[2],o10[1]*o10[2]]
dt2["Subtotal1"] = dt2["Subtotal1"].apply(increase)
dt2["Total"] = dt2['Subtotal1']+dt2['Subtotal2']+dt2['Subtotal3']
dt2 = dt2.drop(['Subtotal1','Subtotal2','Subtotal3'], axis=1)
dt2

Num_orden   Total
n1        1.0  688.33
n2        2.0  504.46
n3        3.0  374.80
n4        4.0  502.57

4. Use filter to eliminate all words that are shorter than 4 letters from a list of words
`list='the notion of a lambda function goes all the way back to the origin of computer science'`

In [7]:
# Código de solución estudiante 1: Ana María A.
lista='the notion of a lambda function goes all the way back to the origin of computer science'
lista = lista.split()
r4 = list(filter(lambda x:len(x)>4, lista))
r4

['notion', 'lambda', 'function', 'origin', 'computer', 'science']

In [36]:
# Código de solución estudiante 2
sentence='the notion of a lambda function goes all the way back to the origin of computer science'

words = sentence.split()

four_letters = list(filter(lambda x:len(x)>4,words))
four_letters

['notion', 'lambda', 'function', 'origin', 'computer', 'science']

5. Use filter to determine the percentage of Fahrenheit temperatures in a list are within the range 32 to 80

In [8]:
import numpy as np
np.random.seed(55555)
temperatures = np.random.uniform(25,110,30)
print(temperatures)

[ 35.97387961  99.13294268  92.6178302   99.69549478  63.21119535
  73.90387697  95.50028838  99.21476553  36.98251238 101.45813729
 100.5917418   89.38159435  89.52156589  83.8084752   28.37990868
  68.75395211  45.86132067  36.58307493  56.32208365  33.96219302
  45.29071318  74.86289938  66.51091383  88.19316186  94.26635864
  46.83131624 109.60744472 109.68427993  44.55796499  92.84146259]


In [9]:
# Código de solución estudiante 1: Ana María A.
r5 = list(filter(lambda x: x>32 and x<80, temperatures))
r5

[35.97387961379455,
 63.211195349983264,
 73.90387696517755,
 36.982512376595906,
 68.75395211338406,
 45.86132066984196,
 36.58307493022292,
 56.322083650154724,
 33.9621930206693,
 45.29071317816652,
 74.86289938282341,
 66.51091382521807,
 46.831316244170544,
 44.55796498523391]

In [37]:
# Código de solución estudiante 2
np.random.seed(55555)
temperatures = np.random.uniform(25,110,30)

result = list(filter(lambda x:x>=32,temperatures))
result2 = list(filter(lambda x:x<=80,result))
print('Numeros pares de la lista:',result2)

Numeros pares de la lista: [35.97387961379455, 63.211195349983264, 73.90387696517755, 36.982512376595906, 68.75395211338406, 45.86132066984196, 36.58307493022292, 56.322083650154724, 33.9621930206693, 45.29071317816652, 74.86289938282341, 66.51091382521807, 46.831316244170544, 44.55796498523391]


6. Use reduce to find the lower left corner (minimum x and minimum y value) for a list of point locations
> **Hint**: Explore the command `np.minimum.reduce` [link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ufunc.reduce.html)

In [10]:
np.random.seed(55555)
point_xy = np.random.randint(0,100,[30,2])
print(point_xy)

[[17 97]
 [22 33]
 [37 46]
 [57 28]
 [11 25]
 [14  2]
 [74 16]
 [12 37]
 [35 21]
 [66 65]
 [86 58]
 [67 81]
 [ 0 48]
 [28 66]
 [76 22]
 [46 47]
 [64  7]
 [88 94]
 [65 13]
 [75 89]
 [23 17]
 [36 63]
 [62 36]
 [64 17]
 [18 19]
 [88 41]
 [21 49]
 [98 36]
 [81 73]
 [62 90]]


In [11]:
# Código de solución estudiante 1: Ana María A.
np.minimum.reduce(point_xy)

array([0, 2])

In [38]:
# Código de solución estudiante 2
np.random.seed(55555)
point_xy = np.random.randint(0,100,[30,2])
np.minimum.reduce(point_xy)

array([0, 2])